### ISSUE TITLE
Box-sizing css needs review

### ISSUE THREAD

**Issue by iphutch** [kommandr/browser-extension#14]
There is an `/n` character in the description for Box-sizing

```css
* {
  box-sizing: border-box;
}
```

https://css-tricks.com/box-sizing/
