### ISSUE TITLE
CSS needs review

### ISSUE THREAD

**Issue by iphutch** [kommandr/browser-extension#8]
```css
.c-media {
  /* the default styles */
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
}
```
Gap is missing
